package com.github.sejoung.codetest.tryfinally;

public class SecondException extends RuntimeException {
}
